#!/usr/bin/with-contenv zsh
cd "${HOME}"
exec /home/${NB_USER}/.asdf/shims/jupyter lab \
    --notebook-dir="${HOME}" \
    --ip=0.0.0.0 \
    --no-browser \
    --allow-root \
    --port=8888 \
    --ServerApp.token="" \
    --ServerApp.password="" \
    --ServerApp.allow_origin="*" \
    --ServerApp.base_url="${NB_PREFIX}" \
    --ServerApp.terminado_settings='shell_command=["/bin/zsh"]' \
    --ServerApp.authenticate_prometheus=False
